// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA9irNr6tjD730QDD9cjFCjHs8uXKDTcxE",
    authDomain: "demo1-4b8c1.firebaseapp.com",
    projectId: "demo1-4b8c1",
    storageBucket: "demo1-4b8c1.firebasestorage.app",
    messagingSenderId: "414164341416",
    appId: "1:414164341416:web:6901f048dc261ac921a89d",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtPQ8qFibX0qjRDoqdewNq58l1w5fCk',
    appId: '1:414164341416:android:3f700f1bdd4da6c521a89d',
    messagingSenderId: '57136751205',
    projectId: 'demo1-4b8c1',
    storageBucket: 'demo1-4b8c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jlcZ62IAiada3hF6qlE2csHMH1QSXjg',
    appId: '1:57136751205:ios:af30eaec87a28dffff5c8c',
    messagingSenderId: '57136751205',
    projectId: 'demo1-4b8c1',
    storageBucket: 'esd-monitoring-2db90.appspot.com',
    // iosBundleId: 'com.avic.avicSmartfactory',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyA2jlcZ62IAiada3hF6qlE2csHMH1QSXjg',
  //   appId: '1:57136751205:ios:af30eaec87a28dffff5c8c',
  //   messagingSenderId: '57136751205',
  //   projectId: 'esd-monitoring-2db90',
  //   storageBucket: 'esd-monitoring-2db90.appspot.com',
  //   iosBundleId: 'com.avic.avicSmartfactory',
  // );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDIDlGY0i_kqv1XurAzfdu0oTzYTzheIs',
    appId: '1:57136751205:web:08f0f412757a6c24ff5c8c',
    messagingSenderId: '57136751205',
    projectId: 'esd-monitoring-2db90',
    authDomain: 'esd-monitoring-2db90.firebaseapp.com',
    storageBucket: 'esd-monitoring-2db90.appspot.com',
  );
}
